### ISSUE TITLE
Secure web server logging?

### ISSUE THREAD

**Issue by bjlittle** [SciTools-incubator/artifact-upload-handler#2]
Should we consider adding logging to the secure web server?

In particular, within the [post](https://github.com/SciTools-incubator/artifact-upload-handler/blob/master/handler/artifact_upload_handler.py#L62) method of the `ArtifactUploadHandler` no action is taken when the CI token fails.

Perhaps, we should have some awareness (through logging) of the web server status.

**Comment by DPeterK** [comment]
👍 

Or we could see if we could send a message back to the requesting process to warn it that the upload it requested could not be completed.

**Comment by pelson** [comment]
Solved.
